### ISSUE TITLE
Error in gemspec file 

### ISSUE THREAD

**Issue by alcamla** [techery/danger-localization-guard-plugin#1]
Hi, I am trying to install the plugin through bundle, and I am getting the following error: 

You have one or more invalid gemspecs that need to be fixed.
The gemspec at
/usr/local/lib/ruby/gems/2.5.0/bundler/gems/danger-localization-guard-plugin-52ce370b4d7f/danger-localization_guard.gemspec
is not valid. Please fix this gemspec.
The validation error was '"https://github.com/Max Sysenko/danger-localization_guard" is not a
valid HTTP URI'

Thi given url does not exist any longer.

Thanks in advance for your help!

**Comment by MaxRandom** [comment]
Hi @alcamla 
I've fixed URL in gemspec and created a new release(0.0.5). Please, check it.

**Comment by alcamla** [comment]
Now I am able to install, thanks for the quick fix
